### ISSUE TITLE
Allow to be run on existing install

### ISSUE THREAD

**Issue by dracos** [staticsafe/mastible#7]
I haven't submitted a PR for this yet (thought I'd probably done enough!) but wondered what you thought about changes so that you could rerun this playbook on an existing install and not have it e.g. wipe the database. This would make it much easier to update mastodon as you could update the version number here, rerun and it would update dependencies, precompile assets and the other needed stuff.

Here's the commit I've done, on top of my other changes, which I have used successfully to upgrade to v2.4.4: https://github.com/dracos/mastible/commit/allow-rerunning – it moves the install bits (secret generation, db wipe/reload, gets first LE cert) to separate tasks and only calls them if you run ansible-playbook with `--extra-vars='install=true'` (there might be a nicer way of doing that, I'm no ansible expert).

**Comment by packetcat** [comment]
I looked the changes over and they look fine to me, you can go ahead with a pull request!
